-- HeyHeyDive — Member system
--
-- 1. Link bookings to a Supabase Auth user when the admin confirms the booking.
--    The admin handler creates the auth account (or reuses an existing one with
--    the same email) and writes auth.users.id into bookings.user_id.
--
-- 2. Certificates table — admin uploads PADI / AIDA card images for a member.
--    Members can list & view their own; admins can do everything.
--
-- 3. Private `certificates` storage bucket. Members fetch their files via
--    short-lived signed URLs generated by a server action that re-checks
--    ownership; admins also fetch via signed URLs from the admin client.

-- ─────────────────────────────────────────────────────────────
-- bookings: nullable user_id linking to auth.users
-- ─────────────────────────────────────────────────────────────
alter table public.bookings
  add column if not exists user_id uuid references auth.users(id) on delete set null;

create index if not exists bookings_user_id_idx on public.bookings (user_id);

-- Owners (matching user_id) can read their own bookings. Admin policy unchanged.
drop policy if exists "bookings owner read" on public.bookings;
create policy "bookings owner read" on public.bookings for select
  using (user_id is not null and user_id = auth.uid());

-- ─────────────────────────────────────────────────────────────
-- certificates
-- ─────────────────────────────────────────────────────────────
create table if not exists public.certificates (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  system text not null check (system in ('aida','padi','other')),
  level text not null,
  cert_number text,
  issued_date date,
  image_path text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists certificates_user_id_idx on public.certificates (user_id);
create index if not exists certificates_created_at_idx on public.certificates (created_at desc);

drop trigger if exists certificates_touch on public.certificates;
create trigger certificates_touch before update on public.certificates
  for each row execute function public.touch_updated_at();

alter table public.certificates enable row level security;

drop policy if exists "certificates owner read" on public.certificates;
create policy "certificates owner read" on public.certificates for select
  using (user_id = auth.uid());

drop policy if exists "certificates admin all" on public.certificates;
create policy "certificates admin all" on public.certificates for all
  using (public.is_admin()) with check (public.is_admin());

-- ─────────────────────────────────────────────────────────────
-- Storage bucket `certificates` — private; access via signed URLs
-- ─────────────────────────────────────────────────────────────
insert into storage.buckets (id, name, public)
values ('certificates', 'certificates', false)
on conflict (id) do update set public = false;

-- No public read policy. Uploads & signed URL generation happen via the
-- service-role client (server-side, after we verify ownership / admin).
